name: Deploy
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy client web
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
    
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link Vercel Project
        run: vercel link --yes --project=prt-tracker-fe --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: | 
            vercel deploy --prod \
            --env NEXT_PUBLIC_API_HOST="https://prt-tracker-fe.vercel.app/" \
            --env API_KEY=${{ secrets.API_KEY }} \
            --env API_HOST="https://prt-tracker-zing.deno.dev" \
            --build-env NEXT_PUBLIC_API_HOST="https://prt-tracker-fe.vercel.app/" \
            --build-env API_KEY=${{ secrets.API_KEY }} \
            --build-env API_HOST="https://prt-tracker-zing.deno.dev" \
            --token=${{ secrets.VERCEL_TOKEN }}